import { getSupabaseClient } from '../../utils/supabase'
import type { ExcuseAbsenceRequest } from '~/types/attendance'

export default defineEventHandler(async (event) => {
  const client = getSupabaseClient()
  const user = event.context.user

  if (!user) {
    throw createError({
      statusCode: 401,
      message: 'Unauthorized',
    })
  }

  try {
    const body = await readBody<ExcuseAbsenceRequest>(event)
    const { absence_id, is_excused, grant_makeup_credit } = body

    if (!absence_id || is_excused === undefined) {
      throw createError({
        statusCode: 400,
        message: 'Missing required fields',
      })
    }

    // Verify user has permission (staff or admin only)
    const { data: profile } = await client
      .from('profiles')
      .select('user_role')
      .eq('id', user.id)
      .single()

    if (!profile || !['admin', 'staff'].includes(profile.user_role)) {
      throw createError({
        statusCode: 403,
        message: 'Permission denied. Only admin and staff can excuse absences.',
      })
    }

    // Get absence record
    const { data: absence, error: absenceError } = await client
      .from('absences')
      .select('*')
      .eq('id', absence_id)
      .single()

    if (absenceError || !absence) {
      throw createError({
        statusCode: 404,
        message: 'Absence not found',
      })
    }

    // Update absence record
    const { data: updatedAbsence, error: updateError } = await client
      .from('absences')
      .update({
        is_excused,
        excused_by: user.id,
        excused_at: new Date().toISOString(),
      })
      .eq('id', absence_id)
      .select(`
        *,
        student:students(
          id,
          first_name,
          last_name
        ),
        class_instance:class_instances(
          id,
          name
        )
      `)
      .single()

    if (updateError) throw updateError

    // Update attendance status to excused if it exists
    await client
      .from('attendance')
      .update({ status: is_excused ? 'excused' : 'absent' })
      .eq('student_id', absence.student_id)
      .eq('class_instance_id', absence.class_instance_id)
      .eq('attendance_date', absence.absence_date)

    // The makeup credit will be automatically generated by the database trigger
    // if grant_makeup_credit is true in the excuse logic

    return {
      success: true,
      absence: updatedAbsence,
      message: is_excused ? 'Absence excused successfully' : 'Absence unexcused',
    }
  } catch (error: any) {
    console.error('Error excusing absence:', error)
    throw createError({
      statusCode: error.statusCode || 500,
      message: error.message || 'Failed to excuse absence',
    })
  }
})
